apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/namespaces
  - ../base/storage
  - ../base/traefik
  - ../base/cert-manager

commonLabels:
  environment: production
