apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../base/storage
  - ../base/traefik
  - ../base/cert-manager
  - certificates.yaml

commonLabels:
  environment: production
