apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drupal

resources:
  - ../base/drupal
  - secrets.yaml

patches:
  # Production-specific replica count
  - target:
      kind: Deployment
      name: drupal
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
